CREATE TABLE POSTS(
    id UNIQUEIDENTIFIER PRIMARY KEY,
    title NVARCHAR(150) NOT NULL,
    subtitle NVARCHAR(50) NOT NULL,
    author NVARCHAR(75) NOT NULL,
	body NVARCHAR(800) NOT NULL,
	image_path VARCHAR(100) NULL,
	timestamp DATETIME NOT NULL DEFAULT(GETDATE()),
	user_id UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id)
);